services:
  frontend:
    image: nginx
    ports:
      - "80:80"
    networks:
      test:
        ipv4_address: 192.168.0.2


  mysqldb:
    image: mysql
    ports:
      - "3306:3306" 
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: todos
    networks:
      test:
        ipv4_address: 192.168.0.3

volumes:
  dbvol:

networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1